package tester;

import org.hibernate.SessionFactory;
import static utils.Hibernateutils.getFactory;

import java.util.Scanner;

import dao.DepartmentDao;
import dao.DepartmentDaoImpl;
import pojos.Department;

public class GetDepartmentDetails {

	public static void main(String[] args) {
		try (SessionFactory sf = getFactory(); java.util.Scanner sc = new Scanner(System.in)) {
			DepartmentDao dao = new DepartmentDaoImpl();
			System.out.println("Enter dept name");
			Department department = dao.getDepartmentDetails(sc.next());
			System.out.println("Dept details " + department);
			// confirm the proxy
			System.out.println("Name of the Proxy class generated by hibernate using helper lib @ run time "
					+ department.getEmpList().getClass());
			
			System.out.println("Emps from dept ");
			department.getEmpList().forEach(e->System.out.println(e));
		} // sf.close() --> cleaning up DBCP (db conn pool)
		catch (Exception e) {
			e.printStackTrace();
		}

	}

}
